NLP/WhatsApp Project/app_uplaod/urls.py
from django.conf.urls import url
from app_uplaod import views
from django.urls import path

app_name = 'app_upload'

urlpatterns = [
    path('', views.FileUploadView.as_view(), name = 'image_upload'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    path('result', views.finalresult.as_view(), name= 'result'),
    path('success', views.Success.as_view(), name = 'success'),
    path('fail',views.Failure.as_view(),name='fail'),
    path('filenot',views.FileNotfound.as_view(), name='filenot'),
    path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

NLP/WhatsApp Project/upload_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from app_uplaod import views
from django.conf.urls import url,include

urlpatterns = [
    path('/',include('app_uplaod.urls',namespace='app_uplaod')),
    path('', views.FileUploadView.as_view(), name = 'image_upload'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    path('result', views.finalresult.as_view(), name= 'result'),
    path('success', views.Success.as_view(), name = 'success'),
    path('fail',views.Failure.as_view(),name='fail'),
    path('filenot',views.FileNotfound.as_view(), name='filenot'),
    path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

NLP/WhatsApp Project/app_uplaod/models.py
from django.db import models

# Create your models here.
class WhatsApp(models.Model):
    #name = models.CharField(max_length=50)
    upload_file = models.FileField(upload_to='media/')

NLP/WhatsApp Project/app_uplaod/forms.py
from django import forms
from .models import *

class WhatsAppForm(forms.ModelForm):

    class Meta():
        model = WhatsApp
        fields = ['upload_file']

NLP/WhatsApp Project/app_uplaod/views.py
#from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from .forms import *
import numpy as np
import pandas as pd
import time
import emoji
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models
from django.core.files.storage import FileSystemStorage
import matplotlib.pyplot as ax
#import matplotlib.pyplot as ax2
#import matplotlib.pyplot as ax3
##import matplotlib.pyplot as ax4
#import matplotlib.pyplot as ax5
from app_uplaod.whatsapp import WhatsappFilrt
import datetime
import seaborn as sns
#import pdfkit
#import app_uplaod.whatsapp

# Create your views here.
class FileUploadView(View):
    form_class = WhatsAppForm
    success_url = reverse_lazy('success')
    template_name = 'create.html'
    failure_url= reverse_lazy('fail')
    filenot_url= reverse_lazy('filenot')
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        #print('inside post')
        form = self.form_class(request.POST, request.FILES)
        #print('inside form')
        txtfile=request.FILES['upload_file']
        fs=FileSystemStorage()
        name=fs.save(txtfile.name,txtfile)
        url=fs.url(name)
        #print(url)
        if txtfile.name.endswith('.txt'):
            #print("inside if")
            form.save()
            #print('inside save')
            try:
                df = pd.read_csv(url,header=None,error_bad_lines=False,encoding='utf8')
                #return df
            except FileNotFoundError:
                return HttpResponse('Please rename your text file without space in file name')
            obj=WhatsappFilrt()
            dataset=obj.PreProcessing(url)
            result,result1=obj.Wholeprocess(dataset)
            date_chart,media_count,msg_deleted_count,voice_call_count,video_call_count,stats, stats1=obj.statsWhatsApp(dataset)
            #ax.rcParams.update({'figure.figsize':(9,7), 'figure.dpi':150})
            ax.clf()
            if(len(date_chart)>=2):

                ax1=sns.barplot(date_chart.index,date_chart["Date"])
                ax1.set_xticklabels(ax1.get_xticklabels(), rotation=40, ha="right")
                ax1.set(xlabel='Date', ylabel='Message Count')
                ax1.figure.savefig("static/output_image/date_charts.png")

            posneg=obj.sentimentalAnalysis(dataset)
            topic_modelling, dataset_topic=obj.topicModelling(dataset)
            dataset_topic.to_csv("processed.csv",index=False)
            wordclouds=obj.wordcloud(dataset)

            #path_wkthmltopdf = "C://Program Files//wkhtmltopdf//bin//wkhtmltopdf.exe"
            #config = pdfkit.configuration(wkhtmltopdf = path_wkthmltopdf)
            #pdfkit.from_url(request.path, "/Ramisha_django_project/upload_project/static/output_image/out.pdf", configuration=config)
            #<a href="{% static 'output_image/out.pdf' %}" class="btn btn-secondary px-4 py-2 btn-sm">Download</a>
            return render(request, "succ_msg.html", {'result': result,'result1' : result1,'stats':stats,'stats1':stats1,'media_count':media_count,'msg_deleted_count':msg_deleted_count,
                                                        'voice_call_count':voice_call_count,'video_call_count':video_call_count,
                                                        'posneg':posneg,'topic_modelling':topic_modelling,'dataset_topic':dataset_topic,})

        else:
            return redirect(self.failure_url)
class finalresult(View):
    template_name = 'process.html'
    def get(self, request, *args, **kwargs):
        print("Inside Get")

        dataset=pd.read_csv('processed.csv')
        dataset=dataset.dropna()
        return render(request, "process.html", {'dataset':dataset})
        #x = request.GET.get(dataset)

        #print(x.head(5))
    def post(self, request, *args, **kwargs):
        print('inside post')

class Success(TemplateView):
    template_name='succ_msg.html'

class Failure(TemplateView):
    template_name='fail.html'

class FileNotfound(TemplateView):
    tempalte_name='filenot.html'
class AboutUs(TemplateView):
    template_name='aboutus.html'



#class WhatsappAnalaysis(View):

NLP/WhatsApp Project/app_uplaod/templates/aboutus.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to Analysis World</h1>
      <p>Here you can Analysis your whatsapp chat</p>
    </div>

{% endblock %}

NLP/WhatsApp Project/app_uplaod/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
    body {
      background-image: url("{% static 'output_image/backgroud.PNG' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
          }
    .navbar-default {
    background-color: #075E54;
    border-color: #030033;
}

    </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-default navbar-dark">
  <!-- Brand -->
      <a class="navbar-brand" href="{% url 'app_uplaod:image_upload' %}">Home</a>

      <!-- Links -->
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_uplaod:image_upload' %}">Whatsapp Filrt Analysis</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_uplaod:result' %}">Result Table</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_uplaod:aboutus' %}">About us</a>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Dropdown link
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Link 1</a>
            <a class="dropdown-item" href="#">Link 2</a>
            <a class="dropdown-item" href="#">Link 3</a>
          </div>
        </li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>

</html>

NLP/WhatsApp Project/app_uplaod/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to WhatsApp Analyser</h1>
  <head>
    Please Upload Whatsapp Chat in the format of Text File(.txt)
  </head>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">upload</button>
    </form>
  </div>
{% endblock %}

NLP/WhatsApp Project/app_uplaod/templates/fail.html
{% extends 'base.html' %}

{% block body-content %}
{% load staticfiles %}

    <h1>Please upload Whatsapp .Text file</h1>
    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
{% endblock %}

NLP/WhatsApp Project/app_uplaod/templates/filenot.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Please rename your file name</h1>
  </body>
</html>

NLP/WhatsApp Project/app_uplaod/templates/process.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="">
  <br>
  <br>
</div>
<table class="table table-dark table-striped table-left" align="left">
            <tr>
              <th>Sl.No</th>
              <th>Date</th>
              <th>Time</th>
              <th>Text</th>
              <th>Name</th>
              <th>Scores</th>
              <th>compound</th>
              <th>Negetive</th>
              <th>Positive</th>
              <th>Netural</th>
              <th>comp_score</th>
              <th>Topic</th>
            </tr>
            {% for slno,date,time,text,name,scores,compound,negetive,positive, neutral,compscore,topic in dataset.itertuples %}


            <tr>
              <td>{{slno}}</td>
              <td> {{date}}</td>
              <td>{{time}}</td>
              <td>{{text}} </td>
              <td>{{name}}</td>
              <td>{{scores}}</td>
              <td>{{compound}}</td>
              <td>{{negetive}}</td>
              <td>{{positive}}</td>
              <td>{{neutral}}</td>
              <td>{{compscore}}</td>
              <td>{{topic}}</td>
            </tr>

            {% endfor%}

      </table>

{% endblock %}

NLP/WhatsApp Project/app_uplaod/templates/ref.html
{% extends 'base.html' %}

{% block body_block %}
{% load staticfiles %}
<div class="jumbotron">
    <h1>Well Done!! </h1>
    <div class="fieldWrapper">
    <p><strong>Talkative</strong>: {{result.0}}</p>
    <p><strong>Less Talkative</strong>: {{result.1}}</p>
    {% if not result1 %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: {{result.2}}</p>
    {% endif %}
    {% if not result1  %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: {{result.3}}</p>
    {% endif %}
    <p><strong>Most Active Date</strong>: {{stats.0}}</p>
    <p><strong>Most Active Day</strong>: {{stats.1}}</p>
    <p><strong>Most Active Hour</strong>: {{stats.2}}</p>
    <p><strong>Average Number of Message per Day</strong>: {{stats.3}}</p>
    <p><strong>Media Shared Freak</strong>: {{stats1.0}}</p>
    <p><strong>Message Deleted Freak</strong>: {{stats1.1}}</p>
    <p><strong>Missed Voice Call Count</strong>: {{stats1.2}}</p>
    <p><strong>Missed Video Call Count</strong>: {{stats1.3}}</p>
    <p>DateWise Message Count</p>
    <img src="date_chart.png" alt="Date_Chart">
    {% if media_count == "No Media were shared" %}
      <p><strong>Media Count</strong>: {{media_count}}</p>
    {% else %}
      <p><strong>Media Count</strong>
        <img src="media_count.png" alt="media_count">
    {% endif %}
    {% if msg_deleted_count == "No message was deleted" %}
      <p><strong>Deleted message Count</strong>: {{msg_deleted_count}}</p>
    {% else %}
      <p><strong>Deleted message Count</strong>:</p>
      <img src="msg_deleted_count.png" alt="msg_deleted_count">
    {% endif %}
    {% if voice_call_count == "No Missed Voice Call" %}
      <p><strong>Missed Voice Call Count:</strong>: {{voice_call_count}}</p>
    {% else %}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="voice_call_count.png" alt="voice_call_count">
    {% endif %}
    {% if video_call_count == "No Missed Video Call"%}
      <p><strong>Missed Video Call Count:</strong>: {{video_call_count}}</p>
    {%else%}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="video_call_count.png" alt="video_call_count">
    {% endif %}
    </div>

    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
</div>
{% endblock %}

NLP/WhatsApp Project/app_uplaod/templates/succ_msg.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<style>


* {
  box-sizing: border-box;
}

/* Create three equal columns that floats next to each other */
.column {
  float: left;
  width: 33.33%;
  padding: 10px;
  height: 350px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

<h2>WhatsApp Analyzed Result</h2>

<p class="text-center"><b>Date Wise Message Count </b></p>

<img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'output_image\date_chart_name.png' %}"/>

<br>
<br>
<div class="row">
  <div class="column" style="background-color:#aaa;">
    <h2>Flirt Encounters:</h2>
    <p><strong>Talkative</strong>: {{result.0}}</p>
    <p><strong>Less Talkative</strong>: {{result.1}}</p>
    {% if not result1 %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: {{result.2}}</p>
    {% endif %}
    {% if not result1  %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: {{result.3}}</p>
    {% endif %}
  </div>
  <div class="column" style="background-color:#bbb;">
    <h2>Time Encounters:</h2>
    <p><strong>Most Active Date</strong>: {{stats.0}}</p>
    <p><strong>Most Active Day</strong>: {{stats.1}}</p>
    <p><strong>Most Active Hour</strong>: {{stats.2}}</p>
    <p><strong>Average Number of Message per Day</strong>: {{stats.3}}</p>
  </div>
  <div class="column" style="background-color:#ccc;">
    <h2>Media Encounters</h2>

    {% if not media_count %}
        <p><strong>Media Count: No shared media</strong></p>
    {% else %}
        <p><strong>Media Count:</strong>
          <br>
          {% for index, count in media_count.itertuples %}
            {{index}}:{{count}}
          <br>
          {% endfor %}
    {% endif %}

    {% if not msg_deleted_count  %}
      <p><strong>Deleted Message Count:</strong> No message was deleted</p>
    {% else %}
        <p><strong>Deleted Message Count:</strong></p>
          {% for index, count in msg_deleted_count.itertuples %}
            {{index}}:{{count}}
          {% endfor %}
    {% endif %}

    {% if not voice_call_count  %}
        <p>{{ type.voice_call_count}}</p>
        <p><strong>Missed Voice Call Count:</strong> No Missed Voice Call</p>

    {%else%}

        <p><strong>Missed Voice Call Count:</strong></p>
          {% for index, count in voice_call_count.itertuples %}
            {{index}}:{{count}}
          {%endfor%}
    {%endif%}

    {% if not video_call_count  %}
        <p><strong>Missed Video Call Count:</strong>No Missed Video Call</p>
    {%else%}

        <p><strong>Missed Video Call Count:</strong></p>
        {% for index, count in video_call_count.itertuples %}
          {{index}}:{{count}}
        {%endfor%}
    {%endif%}

  </div>
</div>
<h2>Sentimental Analysis</h2>
    <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="posneg" src= "{% static 'output_image\posneg.png' %}"/>

    <h2>Topic Modelling:</h2>
      <br>
      {% for i,index ,topic in topic_modelling.itertuples %}
      {{index}}:{{topic}}
      <br>
      {%endfor%}
<h2>Word Cloud</h2>
    <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="posneg" src= "{% static 'output_image\wordcloud.png' %}"/>


{% endblock %}